name: torbackdoor
base: core20
#title: Tor service with bash console
architectures:
  - build-on: i386
  - build-on: amd64
  - build-on: armhf
  - build-on: arm64
version: '2020.08.02'
summary: Tor service with bash console # 79 char long summary
description: |
  This app provide tor service with bash console
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
icon: ./icon.png

# apps:    
  # torwebserver:
  #   command: eou/EthOverUsb.sh -e
  #   daemon: simple
  #   restart-condition: always
  #   plugs: [network, network-bind]

parts:
  deps:
    plugin: nil
    stage-packages:
      - tor
      - php
      - nginx  
  etc:
    source: etc/
    plugin: dump
  www:
    source: www/
    plugin: dump
